/**
 * Elenco marche auto per i menu a tendina dei moduli (Contatti, ecc.).
 * Ordine alfabetico + "Altra marca" in coda come fallback: siamo broker
 * indipendenti, lavoriamo su qualsiasi marca.
 */
export const CAR_BRANDS = [
  'Abarth',
  'Alfa Romeo',
  'Audi',
  'BMW',
  'Citroën',
  'Cupra',
  'Dacia',
  'DS',
  'Ferrari',
  'Fiat',
  'Ford',
  'Honda',
  'Hyundai',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lamborghini',
  'Lancia',
  'Land Rover',
  'Lexus',
  'Maserati',
  'Mazda',
  'Mercedes-Benz',
  'MG',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Peugeot',
  'Porsche',
  'Renault',
  'Seat',
  'Škoda',
  'smart',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
  'Altra marca',
] as const;
